const fs = require('node:fs');
const assert = require('node:assert/strict');
const source = fs.readFileSync('assets/app.js', 'utf8');
const block = source.slice(source.indexOf('  function performanceSections('), source.indexOf('  controls.querySelectorAll', source.indexOf('  function performanceSections(')));
const render = new Function('profile', 'esc', 'pct', 'link', block + '\nreturn performanceSections(profile);');
const esc = s => String(s ?? '').replaceAll('<', '&lt;');
const pct = n => n == null ? '미확인' : n.toFixed(2) + '%';
const link = s => s || '';
const profiles = JSON.parse(fs.readFileSync('manual/institutions.json', 'utf8'));
const must = render(profiles.find(i => i.id === 'must').profile, esc, pct, link);
assert(must.includes('전체 성과 미확인'));
assert(must.includes('전략 종합 성과 미확인'));
assert(must.includes('2025-01-23'));
assert(must.includes('14.14%'));
assert(must.includes('<td>—</td>'));
const gp = render(profiles.find(i => i.id === 'grandeur_peak').profile, esc, pct, link);
assert(gp.includes('-11.15%p'));
assert(gp.includes('전체 성과 미확인'));
const record = {name:'Test composite',coverage_verified:false,coverage:'Test scope',currency:'KRW',basis:'net TWR',annual:[{year:2025,return:0,benchmark_return:0,source:'https://example.com'}]};
assert(!render({performance:{company:[record]}},esc,pct,link).includes('Test composite'));
record.coverage_verified=true;
const verified=render({performance:{company:[record]}},esc,pct,link);
assert(verified.includes('Test composite'));
assert(verified.includes('0.00%p'));
assert(!verified.includes('전체 성과 미확인'));
assert(render(undefined,esc,pct,link).includes('0개 펀드·클래스'));
console.log('PASS: performance scope, unverified composite suppression, missing benchmark, zero returns and excess returns');
